swagger: '2.0'
info:
  version: '1.0.0'
  title: Football Results Analyser
  description: An API for the Football Results Analyser
  contact:
    name: Mark Fowler
    email: themindbadger@gmail.com
    url: http://yettobedecided
host: fra.mindbadger
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /seasons:
    get:
      description: Returns all seasons
      operationId: findSeasons
      produces:
        - application/json
      responses:
        '200':
          description: season response
          schema:
            type: array
            items:
              $ref: '#/definitions/season'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
    post:
      description: Creates a new season.
      operationId: addSeason
      produces:
        - application/json
      parameters:
        - name: season
          in: body
          description: Season to be added
          required: true
          schema:
            $ref: '#/definitions/season'
      responses:
        '200':
          description: pet response
          schema:
            $ref: '#/definitions/season'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
  /seasons/{seasonNumber}:
    get:
      description: Returns a season
      operationId: findSeasonById
      produces:
        - application/json
      parameters:
        - name: seasonNumber
          in: path
          description: ID of season to fetch
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: season response
          schema:
            $ref: '#/definitions/season'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
definitions:
  season:
    type: object
    required:
      - seasonNumber
    properties:
      seasonNumber:
        type: integer
        format: int64
  errorModel:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
